version: "3.0"
services:
  elasticsearch:
    container_name: es
    image: docker.elastic.co/elasticsearch/elasticsearch:8.9.2
    volumes:
      - ./esdata:/usr/share/elasticsearch/data
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
      - http.port=19200
    network_mode: "host"
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:8.9.2
    environment:
      - ELASTICSEARCH_HOSTS=http://0.0.0.0:19200
      - SERVER_PORT=19201
    network_mode: "host"
    depends_on:
      - elasticsearch

volumes:
  esdata:
